from pathlib import Path
from html import escape
import json

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'results/fresh'; PAGE=OUT/'artifact.html'
def fig(n,cap):
 p=OUT/'figures'/f'{n}.png'
 return f"<figure><img src='figures/{p.name}'><figcaption>{escape(cap)}</figcaption></figure>" if p.exists() else ''
def table(n,cols=None,limit=24):
 import csv
 p=OUT/'tables'/f'{n}.csv'
 if not p.exists(): return ''
 rows=list(csv.reader(p.open())); h=rows[0]; d=rows[1:]
 if cols:
  ix=[h.index(c) for c in cols if c in h];h=[h[i] for i in ix];d=[[r[i] for i in ix] for r in d]
 d=d[:limit];more=f"<p class='muted'>Showing {len(d)} rows; <a href='tables/{n}.csv'>full CSV</a>.</p>" if len(rows)-1>len(d) else ''
 return '<div class=tablewrap><table><tr>'+''.join(f'<th>{escape(x)}</th>' for x in h)+'</tr>'+''.join('<tr>'+''.join(f'<td>{escape(x)}</td>' for x in r)+'</tr>' for r in d)+'</table></div>'+more
def listing(p):
 s='\n'.join(f"<span class=ln>{i:04d}</span> {escape(x)}" for i,x in enumerate(p.read_text(errors='replace').splitlines(),1))
 return f"<details><summary>{p.relative_to(ROOT)} ({len(s.splitlines())} lines)</summary><pre class=code>{s}</pre></details>"
sources=[ROOT/'src/fresh'/n for n in ['common.R','prepare.R','eda.R','measurement.R','regression.R','structural.R','bayesian.R','prediction.R','secondary.R','robustness.R','reporting.R','validate.R']]
m=json.loads((OUT/'run_manifest.json').read_text());checks=json.loads((ROOT/'results/repository_audit/checks.json').read_text())
html=f'''<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width"><title>Wildboar Compensation Analysis Artifact</title><style>
:root{{--ink:#203040;--blue:#124e66;--teal:#087f73;--bg:#f4f8fa;--card:#fff;--line:#d9e4eb}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,sans-serif}}header{{padding:55px max(24px,calc((100% - 1180px)/2));background:linear-gradient(135deg,#113b55,#087f73);color:#fff}}h1{{font-size:clamp(32px,5vw,58px);line-height:1.08;margin:0 0 16px}}header p{{max-width:900px;font-size:19px;color:#e1f5f1}}nav{{position:sticky;top:0;z-index:2;background:#102b3b;padding:11px max(24px,calc((100% - 1180px)/2));overflow:auto;white-space:nowrap}}nav a{{color:#e1f5f1;text-decoration:none;margin-right:22px}}main{{max-width:1180px;margin:auto;padding:24px}}section{{background:var(--card);border:1px solid var(--line);border-radius:13px;padding:27px;margin:20px 0;box-shadow:0 4px 17px #12344d10}}h2{{font-size:29px;color:var(--blue);margin-top:0}}h3{{color:var(--teal);margin-top:28px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}}.metric{{padding:15px;border-left:4px solid var(--teal);background:#eaf7f5;border-radius:7px}}.metric strong{{display:block;color:var(--blue);font-size:28px}}figure{{margin:22px 0;text-align:center}}figure img{{max-width:100%;max-height:600px;border:1px solid var(--line);border-radius:8px}}figcaption,.muted{{color:#627788;font-size:14px}}.tablewrap{{overflow:auto;border:1px solid var(--line);border-radius:8px}}table{{border-collapse:collapse;width:100%;font-size:14px}}th,td{{padding:8px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}}th{{background:#e7f1f5;color:var(--blue)}}details{{margin:10px 0;border:1px solid var(--line);border-radius:7px;background:#fbfdff}}summary{{cursor:pointer;padding:11px;color:var(--blue);font-weight:650}}pre.code{{margin:0;padding:14px;overflow:auto;background:#10212d;color:#e3edf1;font:12px/1.4 ui-monospace,monospace}}.ln{{display:inline-block;width:42px;color:#7993a3;user-select:none}}.callout{{padding:15px 18px;background:#fff7df;border-left:5px solid #e39a25;border-radius:6px}}a{{color:#08627a}}
</style><header><h1>Compensation application and tolerance toward wild boars</h1><p>Statistical consulting artifact for Mengxi Kou · Fresh R-first analysis release · 17 September 2026</p><p>A browsable record of the complete path from the cleaned workbook through EDA, measurement, structural models, robustness checks, visualisations, reports, and presentation.</p></header><nav><a href=#overview>Overview</a><a href=#eda>EDA</a><a href=#measurement>Measurement</a><a href=#analysis>Analysis</a><a href=#robustness>Robustness</a><a href=#code>Code</a><a href=#reproduce>Reproduce</a></nav><main>
<section id=overview><h2>Executive result</h2><div class=grid><div class=metric><strong>625</strong>matched respondents</div><div class=metric><strong>277 / 348</strong>applicants / non-applicants</div><div class=metric><strong>−0.142</strong>PLS direct path (95% bootstrap CI −0.194 to −0.083)</div><div class=metric><strong>0</strong>proposed indirect intervals excluding zero</div></div><p>Application is negatively associated with several management-related tolerance dimensions. The four questions do not form one interchangeable scale; the safety item behaves differently. The defensible conclusion is a qualified association, not proof that compensation causes lower tolerance.</p><div class=callout><b>Guardrail:</b> CE0 records application, not verified payment. County and survey period are confounded. Mediation, moderation, and AIPW-style results depend on assumptions that this cross-sectional design cannot establish.</div><p><a href=report/Analysis_Report.html>Full HTML report</a> · <a href=report/Analysis_Report.pdf>PDF report</a> · <a href=presentation/Wildboar_Consulting_Presentation.pptx>PowerPoint</a> · <a href=presentation/Speaker_Notes.md>speaker notes</a></p></section>
<section id=eda><h2>1. Data foundation and EDA</h2><p>The authoritative workbook has a 625-row Input Data sheet and a 626-row Raw data sheet containing a header/response layer. All IDs match one-to-one. The duplicate Python workbook is byte-identical. The retained data contain 160 Baoxing and 465 Qingchuan respondents; reasons for excluding 49 initial interviews are not available.</p><h3>Preparation choices</h3><ul><li>Tol2 and Tol3 remain as stored; Mengxi confirmed they are already reverse-coded and raw Chinese responses verify the mapping.</li><li>Missing descriptive-word zeros become missing. No nonexistent word is imputed.</li><li>CE1/CE2 stay structurally missing for non-applicants. Percentage values above 100% remain unresolved and are excluded from primary preference models.</li><li>Reporting-institution count is reconstructed from raw choices. Area units remain provisionally mu. Prevention non-use is separate from effectiveness among users.</li></ul>{table('sample_metrics')}{fig('application_by_county','Application proportions differ strongly between the two counties.')}{fig('tolerance_distributions','The four tolerance questions measure distinct substantive dimensions.')}{fig('balance','Observed applicant/non-applicant differences motivate explicit adjustment and sensitivity checks.')}<p>Complete EDA tables cover distributions, missingness, category frequencies, correlations, county/application/park profiles, crop portfolios, raw question families, and descriptive words.</p></section>
<section id=measurement><h2>2. Measurement: EFA, CFA, and PCA</h2><p>The measurement programme tests whether the proposed constructs are meaningful before using them in structural paths. EFA uses development-partition polychoric correlations, minimum-residual extraction, parallel analysis, and oblimin rotation. CFA uses ordinal WLSMV for theory models evaluated on a village-disjoint validation partition and the full sample.</p>{fig('parallel_analysis','Parallel analysis for the eight core attitude/cost items.')}{table('efa_comparison')}{table('cfa_fit')}{table('htmt_scope')}<p>Parallel analysis suggests four factors among eight items, but the item pool cannot support a defensible four-factor CFA with three indicators per factor. The two-factor EFA has an ultra-Heywood warning. CFA shows overlap between tolerance and the proposed cost factor, while formative institutional behaviors should not be forced through reflective HTMT thresholds. The historical HTMT 1.112 is therefore a warning to inspect indicator meaning, not a reason to merge constructs automatically.</p>{table('pca_variance')}{fig('pca_variance','PCA variance profile: descriptive variance reduction, not latent validation.')}</section>
<section id=analysis><h2>3. Statistical analysis choices and outputs</h2><h3>Ordinal and score models</h3><p>Each tolerance item is analyzed separately with cumulative-logit models. Adjustment families proceed from unadjusted to background, resources, and explanatory contemporaneous variables. Township-clustered uncertainty is primary; village clustering is sensitivity. Holm correction is applied within adjustment families.</p>{table('ordinal_associations',['outcome','adjustment','n','estimate','low','high','p_holm'])}{fig('primary_ordinal','Item-level application associations with township-clustered intervals.')}{table('score_associations',['outcome','adjustment','estimate','low','high','p'])}<h3>Bayesian complement</h3><p>Four cumulative-logit township-random-intercept models use weakly informative priors and posterior predictive checks. All four passed the prespecified convergence checks.</p>{table('bayesian_diagnostics')}{table('bayesian_associations')}<h3>PLS-SEM and mechanisms</h3><p>PLS-SEM compares baseline, mediation, extended, four-item, and IC1-only specifications. Formative blocks are evaluated with weights/VIF; reflective blocks with loadings and reliability; structural output includes R², f², SRMR, direct paths, indirect products, and the application-by-cost interaction.</p>{table('pls_quality')}{table('pls_bootstrap_summary',['parameter','estimate','low','high','p_centered','successful'])}{fig('pls_paths','Measurement-and-structural PLS bootstrap intervals.')}</section>
<section id=robustness><h2>4. Secondary analysis, prediction, and stress tests</h2><p>The secondary programme uses applicant experience, agricultural dependence, prevention adoption/effectiveness, insurance preferences, reporting contacts, information channels, crop-specific damage, seasonality, and original descriptive words. Missingness and structural skips are retained explicitly.</p>{table('secondary_associations',['analysis','n','estimate','low','high','p_BH_exploratory'])}{table('prevention_methods')}<h3>Prediction and adjustment</h3><p>Nested township-grouped cross-validation compares a mean benchmark, elastic net, GAM, random forest, and boosting. Fold-local preprocessing avoids leakage. Repeated township cross-fitting estimates an AIPW-style adjusted contrast; overlap and effective sample size are reported.</p>{table('prediction_metrics')}{fig('prediction','Out-of-fold predictive performance for the raw three-item score.')}{table('aipw_summary')}{fig('overlap','Out-of-fold application propensity overlap.')}</section>
<section><h2>5. Specification curve and p-hacking safeguards</h2><p>The specification curve varies prespecified outcomes, measurement summaries, adjustment families, economic transformations, anomaly handling, missingness sensitivity, and clustering. Exact duplicate inputs are deduplicated. Leave-one-township-out and county checks show influence and transport sensitivity.</p>{fig('specification_curve','Reasonable analytical choices shown separately by outcome; this is not proof that p-hacking is absent.')}{table('specification_summary')}{table('county_specific_associations')}<p>A dated decision register, complete result tables, explicit failures, multiplicity handling, and transparent outcome definitions make selective reporting auditable. Nonsignificant MGA differences are reported as no strong evidence of difference, not equivalence.</p></section>
<section id=code><h2>6. Code, line by line</h2><p>Open each source below to inspect its complete line-numbered implementation. The modules run in this order: preparation, EDA, measurement, regression, structural models, Bayesian models, secondary analyses, robustness, adjustment, prediction, reporting, validation.</p>{''.join(listing(p) for p in sources)}</section>
<section id=reproduce><h2>7. Reproduction</h2><pre class=code>Rscript run_project.R --restore
Rscript run_project.R
Rscript run_project.R --render
Rscript run_project.R --verify</pre><p>The generated manifest records source hashes, data hash, seed, session information, and slide counts. Validation passed for coding audit, respondent/application counts, bootstrap success, Bayesian diagnostics, and prediction outputs.</p><p>Data hash: <code>{escape(m.get('data_sha256',''))}</code>. The source audit reports {checks['input_rows']} input rows, {checks['wrong_compensation_proxy_disagreements']} disagreements between CE0 and the obsolete sightings proxy, and {checks['CA1_above_one'] + checks['CA2_above_one']} unresolved percentage anomalies.</p><p>All machine-readable outputs are under <a href=tables/>tables</a>; model objects and logs are under <a href=models/>models/logs</a>. The complete narrative report contains the explicit answers to every Exploratory Contribution question.</p></section>
<section><h2>8. Limitations and next clarification</h2><p>This is a cross-sectional, nonrandom application comparison from two county-period combinations. Unknown sampling/exclusion mechanisms, incomplete payment timing, unresolved percentage and area-unit meanings, weak/overlapping reflective measurement, structural missingness, and potential unmeasured confounding limit causal claims. The most useful next step is to resolve these fieldwork questions with Mengxi and amend affected analyses transparently.</p></section></main><footer style='max-width:1180px;margin:auto;padding:0 24px 60px;color:#627788'>Generated from the fresh analysis release; earlier exploratory work remains preserved.</footer>'''
PAGE.write_text(html,encoding='utf-8');print(PAGE)
